baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'py4SHS'
theme = 'ananke'

resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
#Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Frédérique Rey"
  favicon = ""
  site_logo = "/images/logo.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-electric-blau"
  # body_classes = "Theinhardt bg-near-white"
  recent_posts_number = 6
  custom_css = ["custom.css"]



 
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/frdrqrey"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/metz-theolab/"

